### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by alastairs** [waives/waives.net#11]
**Is your feature request related to a problem? Please describe.**
There is no visibility of the processing taking place at each stage of the pipeline. Previous attempts have involved `Console.WriteLine()` statements, which have been overly verbose, obscuring the output of (e.g.) the sample apps. 

**Describe the solution you'd like**
Writing log messages at different levels which can be enabled/disabled as appropriate for the environment will improve this situation a lot. [LibLog](https://github.com/damianh/LibLog/) is a simple logging abstraction, started to support library authors. [Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging) offers an alternative to LibLog. 

**Describe alternatives you've considered**

**Additional context**

**Comment by markawightman75** [comment]
I think it's important for that either we log by default to the console, or that it's really easy to turn on logging to the console without having to introduce a logging framework. If I'm a user just picking up the SDK, seeing something unexpected or just wanting to see what's going on under the covers, I can get logging to the console really easily.
