### ISSUE TITLE
Remove timer from rate limiter

### ISSUE THREAD

**Issue by phildrip** [waives/waives.net#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alastairs** [comment]
We might be able to remove the rate limiter entirely and replace it with a bulkhead isolation policy from Polly, as [described](https://github.com/App-vNext/Polly/wiki/Transient-fault-handling-and-proactive-resilience-engineering#bulkhead-as-load-segregation-and-relative-resource-allocation) on the Polly wiki. 

Although it's only just kicked off, there's a [mutable bulkhead isolation policy](https://github.com/Polly-Contrib/Polly.Contrib.MutableBulkheadPolicy) in Polly-Contrib. This looks as though it will allow for dynamic capacity adjustment.
