### ISSUE TITLE
Packages don't run in .net framework projects without manual Newtonsoft.Json upgrade 

### ISSUE THREAD

**Issue by markawightman75** [waives/waives.net#38]
**Describe the bug**
When consuming the `Waives.Http` or `Waives.Pipeline` packages in a .net 4.7.1 or 4.7.2 project, the packages are added successfully. But as soon as a method that makes a request is executed, the following error is thrown:
```
{"Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"}
```
Manually upgrading the Newtonsoft.Json package (that has been automatically installed as a dependency)  to >= 10.0.0.0 solves the issue.

**To Reproduce**
To reproduce:
 1. Create a new Console App (.NET Framework) (.net 4.7.2) in VS2017
 2. Install the `Waives.Http` 0.8.2 package
 3. [Note that Newtonsoft.Json.6.0.4 has been installed]
 4. Copy the code below into Program.cs and insert a *valid* client Id and secret
 5. Run and observe the exception written to the console
```
static void Main(string[] args)
        {
            try
            {
                Login().Wait();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"There was an exception: {ex.ToString()}");
            }
            Console.ReadLine();
        }

        static async Task Login()
        {
            var client = new WaivesClient();
            // Replace client Id and secret with valid values to reproduce
            await client.Login("clientid", "clientsecret);
        }
```

**Expected behaviour**
The package methods can be run without manually upgrading Newtonsoft.Json

**System details(please complete the following information):**
 - OS: Windows
 - CLR and version: .NET Framework 4.7.2 (also happens with 4.7.1)
 - SDK version [e.g. 0.8.2]

**Additional context**
In `bin\Debug\netstandard2.0\Waives.Http.deps.json` I found this, which indicates that perhaps something in the dependency resolution is not working correctly.
```
 "Microsoft.AspNet.WebApi.Client/5.2.6": {
        "dependencies": {
          "Newtonsoft.Json": "10.0.1",
          "Newtonsoft.Json.Bson": "1.0.1"
        },
        "
```

**Comment by alastairs** [comment]
As stated in the issue description, it is the `Microsoft.AspNet.WebApi.Client` package pulling in the older version of Newtonsoft.Json, and causing the incompatibility. I've not yet spiked whether we can simply reference Newtonsoft.Json directly from Waives.Http to resolve the issue, but I have spiked removing this package which is no longer maintained.
