### ISSUE TITLE
Code Quality warnings reported in consuming projects

### ISSUE THREAD

**Issue by markawightman75** [waives/waives.net#39]
**Describe the bug**
When using the SDK you get a set of build warnings relating to Microsoft.CodeQuality.Analyzers. These can be ignored but are confusing.

**To Reproduce**
To reproduce:
  1. Create a new Console app using .Net framework 4.7.2
  2. Install the Waives.Http package, version 0.8.2
  3. Compile

You will see a set of 163 warnings like this:

![2018-08-31_09-15-30](https://user-images.githubusercontent.com/5501582/44904248-9e2da280-ad06-11e8-9175-446b075aba9e.png)

**Expected behaviour**
You don't see any build warnings.

**System details(please complete the following information):**
 - Visual Studio: Professional 2015, v 14.0.25431.01 update 3
 - OS: Windows 10
 - CLR and version: .NET Framework 4.7.2
 - SDK version: 0.8.2
 - VS NuGet Package Manager: 3.6.0

**Comment by alastairs** [comment]
We will not be providing support for VS2015 from 1.0.0-beta1 onwards

**Comment by alastairs** [comment]
We should ensure this is not an issue in VS 2017 and higher. I've removed references to VS2015 in teh issue title and description.

**Comment by alastairs** [comment]
The warnings originally reported in the issue description screenshot are specific to VS2015 and so are out of scope for this issue. The library's code quality warnings are reported as follows:

| Runtime | Visual Studio version | Checked | Warnings reported?<br />(No ✅/Yes ❌)  |
| --- | --- | --- | --- |
| .NET Framework 4.7.2 | 16.4 Preview 1 | ✅ | ✅ |
| .NET Core 2.1 | 16.4 Preview 1 | ✅ | ✅ |
| .NET Framework 4.7.2 | 16.3.1 | ✅ | ✅ |
| .NET Core 2.1 | 16.3.1 | ✅ | ✅ |
| .NET Framework 4.7.2 | 15.9.16 | ✅ | ✅ |
| .NET Core 2.1 | 15.9.16 | ✅ | ✅ |

There is no more work required here.
