### ISSUE TITLE
Deprecate support for VS 2015

### ISSUE THREAD

**Issue by alastairs** [waives/waives.net#66]
VS 2015 does not support versions of .NET Core after 1.1, or .NET Framework after 4.6.2. Our platform support is for .NET Framework 4.7+ and .NET Core 2.0+.

**Comment by markawightman75** [comment]
I'm not clear what actually needs _doing_ for this story.

**Comment by alastairs** [comment]
It's mostly documentation, listing the supported platforms, etc. We also need to ensure the NuGet dependencies are set correctly, so the package cannot be installed on unsupported platforms.
